version: "3.9"
services:
  # Services
  webapp:
    image: darchlabs/frontend-hackathon
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      BACKEND_URL: http://metrics:7777
    depends_on:
      - metrics

  metrics:
    image: darchlabs/backend-hackathon
    ports:
      - 7777:7777
    restart: on-failure
    environment:
      SYNCHRONIZERS_API_URL: http://sync:5555
      DATABASE_DSN: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      MIGRATION_DIR: migrations
      PORT: 7777
    depends_on:
      - sync

  # Dependencies
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  sync:
    image: darchlabs/synchronizer-v2:1.8.0
    ports:
      - 5555:5555
    restart: always
    environment:
      INTERVAL_SECONDS: 20
      PORT: 5555
      MIGRATION_DIR: migrations
      DATABASE_DSN: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
